### PR TITLE
fix(imap): LIST/LSUB honor the reference and pattern arguments (#596)

### LINKED ISSUE #596: bug(imap): LIST/LSUB ignore reference and pattern arguments — always return the full mailbox tree (RFC 3501 §6.3.8/9)
## Summary

`LIST` (and `LSUB`) ignore **both** of their arguments — the reference name and the mailbox pattern. Every `LIST` invocation returns the **entire** mailbox tree regardless of what was asked. The `%` (single-hierarchy-level) vs `*` (recursive) wildcard distinction is not implemented, reference-rooted queries are not honored, and even an exact mailbox name (no wildcards) returns the full tree. RFC 3501 §6.3.8 (LIST) / §6.3.9 (LSUB).

## Reproduction (live, against the running dev server)

Logged in as `admin`. Every query below returned an **identical 453-line** untagged `* LIST` dump:

```
c6  LIST "" "%"            -> 453 untagged LIST lines   (should be top-level only: INBOX, Sent Messages, the \Noselect parents)
c7  LIST "INBOX" "%"       -> 453 untagged LIST lines   (should be children of INBOX)
c8  LIST "INBOX/" "%"      -> 453 untagged LIST lines
c9  LIST "" "INBOX"        -> 453 untagged LIST lines   (exact name, NO wildcard -> should be exactly 1 line: INBOX)
c10 LIST "" "%/accounts"   -> 453 untagged LIST lines   (should be just the two ".../accounts" parents)
```

Notably `LIST "" "%"` returns deep entries like `INBOX/accounts/<name>` (hierarchy depth 2), which `%` must never match, and `LIST "" "INBOX"` returns `Sent Messages` and every account mailbox instead of the single `INBOX` entry.

## Expected vs actual

| Query | RFC 3501 expected | Actual |
|---|---|---|
| `LIST "" "%"` | top-level names only (no recursion) | full recursive tree (453) |
| `LIST "" "INBOX"` | exactly `* LIST (...) "/" "INBOX"` | full tree (453) |
| `LIST "INBOX" "%"` | direct children of `INBOX` | full tree (453) |
| `LIST "" "*"` | full tree (this one is correct) | full tree (453) |

## Root cause

The parser **does** extract the reference and pattern correctly:

`src/server/lib/imap/parsers/mailbox-parsers.ts:24-74`
```ts
const referenceName = parseString(context);    // :25
// ... wildcard-aware pattern parse ...
data: { reference: referenceName.value!, pattern: mailboxName.value! }   // :73-74
```

But the dispatch throws both away:

`src/server/lib/imap/handler.ts:251-256`
```ts
case "LIST":
  await this.session.listMailboxes(tag);        // reference + pattern dropped
  break;
case "LSUB":
  await this.session.listSubscribedMailboxes(tag);
  break;
```

`session.listMailboxes(tag)` (`src/server/lib/imap/session.ts:209-213`) forwards only `tag`, and the handler has no pattern parameter at all:

`src/server/lib/imap/mailbox-ops.ts:247-263`
```ts
export async function listMailboxes(tag, store, write) {
  const boxes = await store.listMailboxes();   // every mailbox
  boxes.forEach((box) => {
    write(`* LIST (${getMailboxAttributes(box, boxes)}) "/" "${box}"\r\n`);  // unconditional
  });
  write(`${tag} OK LIST completed\r\n`);
}
```

`listSubscribedMailboxes` (`:265-281`) is identical. So the parsed pattern/reference are computed and discarded; the command can only ever emit the whole tree.

## Why this is a system bug (not user state)

Deterministic protocol behavior, independent of mail content. The arguments are structurally unused. Re-curating mail in the UI cannot change it.

## Impact

- Hierarchy discovery is broken: clients that walk the tree with `LIST "" "%"` → drill into each node with `LIST "<node>" "%"` receive the full 453-entry tree at every step (quadratic traffic, and the `\HasChildren`/`\Noselect` attributes can't be trusted to bound the walk).
- Exact-existence probes via `LIST "" "<name>"` (used by many clients at connect to confirm specific folders like `Sent`, `Drafts`, `INBOX`) return a flood that always "matches," so a client can't tell a present folder from an absent one (compounds the SELECT/STATUS existence gap in the sibling finding filed this session).
- `LSUB "" "*"` returns every mailbox as if subscribed, ignoring subscription state and pattern.

Severity: protocol-correctness / client-compatibility; read path only, no data mutation.

## Proposed fix sketch

1. Thread `reference` + `pattern` from `request.data` through `session.listMailboxes` / `listSubscribedMailboxes` into the `mailbox-ops` handlers (mirror how SELECT threads `request.data.mailbox`).
2. Add an IMAP wildcard matcher: combine reference + pattern, translate to a matcher where `*` matches across the hierarchy delimiter `/` and `%` matches within a single level (not crossing `/`); filter `store.listMailboxes()` through it before emitting `* LIST` lines.
3. For `LSUB`, additionally restrict to subscribed mailboxes (subscription state already persisted via `setMailboxSubscribed`); today it ignores subscription entirely.
4. Keep the existing `getMailboxAttributes` attribute logic; only the set of emitted boxes changes.

Regression tests: `LIST "" "INBOX"` → exactly one line; `LIST "" "%"` → no entry containing a second `/`; `LIST "INBOX" "%"` → only direct children; `LIST "" "*"` → full tree (unchanged).

### PR DESCRIPTION
**Pull request by claoie**
## Problem

`LIST` (and `LSUB`) ignored **both** of their arguments — the reference name and the mailbox pattern — and emitted the **entire** mailbox tree for every query (#596). Consequences:

- `LIST "" "INBOX"` (exact-existence probe many clients send at connect) returned the whole tree, so a client could not tell a present folder from an absent one.
- `LIST "" "%"` recursed across the `/` hierarchy delimiter instead of returning top-level names only.
- `LIST "INBOX" "%"` / `LIST "<node>" "%"` ignored the reference, so hierarchy walks received the full tree at every node (quadratic traffic).
- The parser also truncated mixed patterns at the first wildcard (`INBOX/%` → `INBOX/`, `%/accounts` → `%`), so even threading the parsed value through would have been incomplete.

## Fix

- **Thread** `reference` + `pattern` from the parsed request through `ImapSession.listMailboxes` / `listSubscribedMailboxes` into the `mailbox-ops` handlers (mirrors how SELECT threads its mailbox arg).
- **`matchesListPattern`** (RFC 3501 §6.3.8): reference + pattern are concatenated; `*` matches across the `/` delimiter, `%` matches within a single level only, every other character matches literally. Mailbox attributes are still computed against the full box set, so `\HasChildren` stays correct when child rows are filtered out.
- **Empty-pattern** special case → returns the hierarchy delimiter + root name (`* LIST (\Noselect) "/" "<ref>"`), the delimiter-probe clients send at connect.
- **Parser**: new `parseListMailbox` primitive treats `*`/`%` as ordinary list-mailbox characters, so a mixed pattern is captured whole.

**Out of scope (intentional):** LSUB subscription-state filtering (returning only *subscribed* mailboxes) is a distinct concern from the reference/pattern bug and is left for a separate change.

## Test plan

- [x] `bun run typecheck` — clean
- [x] `bun test src/server` — 962 pass / 4 fail; the 4 fails are the pre-existing `idle-manager.test.ts` cross-file `mock.module` leak (the `idleManager.shutdown is not a function` flake fixed by unmerged #585), identical on `upstream/main`, and **pass in isolation** (`bun test src/server/lib/imap/idle-manager.test.ts` → 3 pass). No new failures from this change.
- [x] New unit tests: `mailbox-list.test.ts` (12 cases over a synthetic hierarchy — `*` crosses `/`, `%` does not, exact-name, `INBOX/%` one-level, non-empty reference concat, empty-pattern probe) + 3 parser regression cases in `mailbox-parsers.test.ts` (embedded-wildcard patterns). 42 pass / 0 fail.
- [x] **Live IMAP wire** — booted the real IMAP server against the local DB, `LOGIN admin`, ran LIST queries on this branch vs `upstream/main` (read-only; LIST does not mutate):

  | Query | `upstream/main` | This branch |
  |---|---|---|
  | `LIST "" "*"` | INBOX (1) | INBOX (1) — full tree, unchanged |
  | `LIST "" "%"` | INBOX (1) | INBOX (1) — top-level (INBOX is top-level) |
  | `LIST "" "<nonexistent>"` | **INBOX (1)** — arg ignored | **0** — pattern honored |
  | `LIST "<nonexistent>/" "%"` | **INBOX (1)** | **0** |
  | `LIST "" "<nonexistent>/%"` | **INBOX (1)** | **0** |
  | `LIST "" "<nonexistent>/*"` | **INBOX (1)** | **0** |

  Baseline returns INBOX for *every* pattern (argument entirely ignored — the bug); this branch returns INBOX only for matching patterns and 0 for non-matching ones. The `%`-vs-`*`-vs-hierarchy discrimination is proven deterministically by the unit tests (the local admin account only has INBOX, so the live wire shows the arg-honored-vs-ignored contrast; the synthetic-tree unit tests cover the wildcard levels).

Note: no browser UI consumes the IMAP LIST path, so the live IMAP wire is the correct verification surface (per the issue's own repro).

Closes #596

### CODE REVIEW

**Comment by claoie** [comment]
CI note: the `test` job will be red on `idle-manager.test.ts` (`idleManager.shutdown is not a function`) — the cross-file `handler-idle.test.ts` `mock.module` leak fixed by the still-open #585. It fails identically on a clean `upstream/main` and **passes in isolation** (`bun test src/server/lib/imap/idle-manager.test.ts` → 3 pass). This PR's own surface (mailbox-list + mailbox-parsers) is green; no new failures. Goes green once #585 merges + rebase. No browser UI consumes the IMAP LIST path, so this was verified on the live IMAP wire (fix-vs-baseline, read-only) — see the test plan.

**Review by hoiekim — APPROVED** [review]
