### PR TITLE
fix(test): handler-idle mock.module leak breaks idle-manager suite on CI

### PR DESCRIPTION
**Pull request by claoie**
## Problem

`bun test src/server` is currently **red on `main`** (and therefore on every open PR rebased onto it): the 4 `IdleManager.notifyNewMail mailbox filtering` tests fail with

```
TypeError: idleManager.shutdown is not a function. (In 'idleManager.shutdown()', 'idleManager.shutdown' is undefined)
```

They pass in isolation but fail in the full suite — the signature of a cross-file `mock.module` leak.

## Root cause

`handler-idle.test.ts` replaced the entire `./idle-manager` module with a partial stub exposing only two methods:

```ts
mock.module("./idle-manager", () => ({
  idleManager: { addIdleSession, removeIdleSession },
}));
```

Bun's `mock.module` is **process-global**. When `idle-manager.test.ts` runs later in the same `bun test` process, its `idleManager` import resolves to that two-method stub, which has no `shutdown()` — so its `beforeEach`/`afterAll` blow up. The existing `afterAll` spread-restore (`mock.module(..., () => ({ ...realIdleManagerModule }))`) did not reliably reinstate the binding for the sibling file.

The collision only became active once both suites landed on `main` — `handler-idle.test.ts` (IDLE termination) and `idle-manager.test.ts` (the notifyNewMail mailbox filter) — turning CI red across the queue.

## Fix

Switch from whole-module `mock.module` to `spyOn` on the real singleton's two methods, restored via `mockRestore()` in `afterAll` — the same pattern that fixed the smtp / auth-rate-limit leak (merged PR #576). `spyOn` mutates the live `idleManager` binding that `session.ts` already holds and reverts cleanly, leaving `shutdown()` and the rest of the singleton intact for sibling files.

Also added the `import "../push"` cycle-busting guard that `idle-manager.test.ts` already uses: importing `./idle-manager` directly (now required for `spyOn`) otherwise triggers the idle-manager ↔ push ↔ server-barrel runtime import cycle (`createPush(realIdleManager)` before the singleton is constructed).

## Scope

One file: `src/server/lib/imap/handler-idle.test.ts`. Test-only; no production code touched. The two stubbed methods were never asserted (`toHaveBeenCalled`), only used as no-ops to keep handler tests off the real singleton, so behavior is unchanged.

## Verification

- `bunx tsc --noEmit`: clean
- `bun test handler-idle.test.ts idle-manager.test.ts` (the leak pair, together): 8 pass / 0 fail
- `bun test src/server` (full suite): **952 pass, 0 fail** (was 948 pass / 4 fail on `main`)

E2E: test-isolation fix on the IMAP IDLE path; no UI surface. Verified at the suite level as above.

### CODE REVIEW

**Comment by reviewoie** [comment]
## Code review — PR 585

**Verdict:** approve (informational — test-only)

**Findings:** 0 total — 0 high, 0 med, 0 low.

Verified the fix end-to-end against `upstream/main`:

- **Leak is real, fix works.** Checked out the base test file under its own path and ran `handler-idle.test.ts → idle-manager.test.ts`: reproduced exactly the 4 failures — `TypeError: idleManager.shutdown is not a function` in the 3 `notifyNewMail` cases plus the `afterAll` shutdown. On HEAD, both file orderings pass (8/8), and the full `bun test src/server` suite is 952 pass / 0 fail — matches the PR's 948/4 → 952/0 claim.
- **spyOn reaches the real call path.** `session.ts` lines 425/445/459 call `idleManager.addIdleSession`/`removeIdleSession` on the live singleton; `spyOn(idleManager, …)` mutates that same instance via the ESM live binding, so the spies are hit and `mockRestore()` in `afterAll` leaves the real methods (including `shutdown()`) intact for sibling files. Same restorable-spy pattern as merged PR #576.
- **No-op behavior unchanged.** Grepped the file: the two spied mocks appear only in `spyOn(...).mockImplementation(() => {})`, `mockClear()`, and `mockRestore()` — never in a `toHaveBeenCalled*` assertion. They were pure stubs before and remain pure stubs, so converting `mock.module` → `spyOn` changes nothing the tests assert.
- **Cycle guard is correct.** `push.ts` imports `idleManager` (line 14) and calls `createPush(...)` at module top level (line 223), so `idle-manager ↔ push ↔ server`-barrel is a genuine init-order cycle. `import "../push"` forces production init order before spying — verbatim the same guard and rationale as `idle-manager.test.ts`.
- **Scope clean.** Exactly one file (`src/server/lib/imap/handler-idle.test.ts`), test-only, no production code.

No blockers.

— Generated by the inbox-reviewer agent.

**Comment by claoie** [comment]
Re-review confirmed (0 findings) — thanks for independently reproducing the leak on base and confirming the 948/4 → 952/0 delta. This unblocks CI for the whole open-PR queue: once merged, rebasing each open PR on main clears the 4 `IdleManager.notifyNewMail` failures with no per-PR change.

**Review by hoiekim — APPROVED** [review]
