### PR TITLE
fix(imap): SEARCH accepts quoted-string arguments (#586)

### LINKED ISSUE #586: bug(imap): SEARCH with a quoted argument (SUBJECT "two words") returns BAD — every quoted/multi-word search fails
## Summary

IMAP `SEARCH` (and `UID SEARCH`) rejects any search key whose argument is a **quoted string**. Since RFC 3501 requires quoting for any value containing a space, this means **every multi-word search fails**, and clients that quote even single-word arguments (Thunderbird, Apple Mail, and most MUAs do) get a hard `BAD` instead of results.

## Reproduction (live IMAP server on :143, admin account)

```
a2 SELECT INBOX
   * 11322 EXISTS

b1 UID SEARCH SUBJECT order            (unquoted, single word)
   * SEARCH 46 50 51 64 71 88 ...      (700+ hits)
   b1 OK SEARCH completed

b2 UID SEARCH SUBJECT "order"          (quoted, single word)
   b2 BAD Invalid search criteria

b3 UID SEARCH SUBJECT "order confirmation"   (quoted, two words)
   b3 BAD Invalid search criteria
```

The only form that works is a bare unquoted single token. Any quoting → `BAD`.

## Expected vs actual

- Expected (RFC 3501 §6.4.4 / §9 — search-key arguments are `astring`, which may be a quoted string): `SUBJECT "order confirmation"` searches subjects for the phrase and returns the matching set.
- Actual: `BAD Invalid search criteria`, no search performed.

## Root cause

Every text/header search-key parser reads its argument with `parseAtom`, which by definition stops at a double-quote:

- `src/server/lib/imap/parsers/primitive-parsers.ts:23-37` — `parseAtom` breaks immediately on `"` (line 28). When the argument starts with `"`, `position === start` → `{ success: false }`.
- `src/server/lib/imap/parsers/search-parsers.ts` — `FROM` (:234), `TO` (:250), `CC` (:266), `BCC` (:282), `SUBJECT` (:298), `BODY` (:314), `TEXT` (:330), `HEADER` field+value (:346/:348) all call `parseAtom(context)` for the value. A failed value parse returns `{ success: false }` for the whole criteria parse → the command handler emits `BAD`.

A correct quoted/unquoted string parser already exists and is unused on this path: `parseString` (`primitive-parsers.ts:118-125`) dispatches to `parseQuotedString` when the next char is `"` and otherwise falls back to `parseAtom`.

This is a SYSTEM bug: pure command-parsing logic, independent of any stored data.

## Proposed fix

Swap `parseAtom` → `parseString` for the **value** reads of `SUBJECT/FROM/TO/CC/BCC/BODY/TEXT` and for both the field and text of `HEADER` in `search-parsers.ts`. (Keep `parseAtom` for the criteria *keyword* itself.) `parseString` already handles the unquoted case, so single-token searches keep working while quoted arguments start parsing. Add a regression test in `search-parsers.test.ts` for `SUBJECT "two words"` and `HEADER "Message-Id" "<...>"`.

### PR DESCRIPTION
**Pull request by claoie**
## Problem

`SEARCH` / `UID SEARCH` rejected any search key whose argument was a **quoted string** with `BAD Invalid search criteria`. Since RFC 3501 requires quoting for any value containing a space, **every multi-word search failed**, and clients that quote even single-word arguments (Thunderbird, Apple Mail, and most MUAs) got a hard `BAD` instead of results.

Closes #586.

## Root cause

The value reads for `FROM`/`TO`/`CC`/`BCC`/`SUBJECT`/`BODY`/`TEXT` and both the field and value of `HEADER` in `parsers/search-parsers.ts` called `parseAtom`, which by definition breaks on `"` (`primitive-parsers.ts:28`). When the argument starts with `"`, `position === start` → the value parse fails → the whole criteria parse fails → the handler emits `BAD`.

## Fix

Swap `parseAtom` → `parseString` for those **value** reads only. `parseString` (`primitive-parsers.ts:118`) dispatches to `parseQuotedString` when the next char is `"` and otherwise falls back to `parseAtom`, so unquoted single-token searches keep working unchanged while quoted arguments start parsing. The criteria **keyword** itself still uses `parseAtom`. Multi-word values flow into the existing `ILIKE` substring match downstream, giving the RFC-correct phrase search — no downstream change needed.

Net: 1 source file (+9 `parseString` value reads, +1 import) + 5 regression tests.

## Test plan

- [x] `bun run typecheck` — clean
- [x] `bunx eslint` (changed files) — clean
- [x] `bun test src/server/lib/imap/parsers/search-parsers.test.ts` — 50 pass / 0 fail. New `quoted-string criteria` block (5 tests: SUBJECT quoted single/phrase, FROM quoted, BODY/TEXT quoted, HEADER quoted field+value) **fails 5/5 on `upstream/main`, passes on this branch** (stash-verified).
- [x] `bun test src/server` — 954 pass / 4 fail. The 4 fails are the pre-existing `IdleManager.notifyNewMail` cross-test `mock.module` leak (fails identically on clean `upstream/main`; passes in isolation) being fixed by the open PR #585 — **not introduced here** (this branch is 949→954 pass, zero new failures).
- [x] **Live-IMAP E2E** — booted the real IMAP server on a high port against the local DB, `LOGIN admin`, `SELECT INBOX` (`* 11322 EXISTS`), read-only `UID SEARCH` (SEARCH does not mutate). Fix vs `upstream/main` baseline, same server/data:
  - `UID SEARCH SUBJECT order` (unquoted control): baseline **OK 813 hits**, fix **OK 813 hits** — unchanged.
  - `UID SEARCH SUBJECT "order"` (quoted single word): baseline **BAD Invalid search criteria**, fix **OK 813 hits** (identical set to the unquoted control).
  - `UID SEARCH SUBJECT "order confirmation"` (quoted phrase): baseline **BAD**, fix **OK 13 hits** (correct narrower phrase subset of the 813).
  - `UID SEARCH HEADER "Subject" "order"` (quoted field + value): baseline **BAD**, fix **OK 813 hits**.
  - Exactly the issue's reproduction resolved: every quoted form went BAD→OK while the unquoted control is byte-for-byte unchanged.

No browser UI consumes the raw IMAP SEARCH path, so the live IMAP wire is the correct verification surface (per CLAUDE.md's "drive the real path when E2E can't reach via browser").

### CODE REVIEW

**Comment by claoie** [comment]
**CI `test` red is the known pre-existing test-isolation flake, not this change.**

The only failures are in `src/server/lib/imap/idle-manager.test.ts` (`TypeError: idleManager.shutdown is not a function`). That's the cross-test `mock.module` leak from `handler-idle.test.ts` bleeding a mocked `idle-manager` into the real `idle-manager.test.ts` suite — already being fixed by open PR #585. It fails identically on clean `upstream/main` and passes when the idle suite runs in isolation.

This PR's own surface is green: `search-parsers.test.ts` 50 pass / 0 fail (incl. the 5 new quoted-string regression tests), and the full `src/server` run is 949→954 pass with **zero new failures** vs baseline. Goes green once #585 merges + this rebases. Nothing to fix here.

**Comment by reviewoie** [comment]
## Code review — PR 590

**Verdict:** approve

**Findings:** 0 blocking — 0 high, 0 med, 1 low (informational).

Verified the diff against the RFC 3501 SEARCH grammar and the actual parser code, ran the test file locally, and read the CI failure log.

### Correctness
`parseString` (`primitive-parsers.ts:118`) dispatches to `parseQuotedString` when the next char is `"` and otherwise falls back to `parseAtom`, so swapping `parseAtom` → `parseString` on the nine value reads (FROM/TO/CC/BCC/SUBJECT/BODY/TEXT values + HEADER field + HEADER value) is correct: unquoted single-token searches keep their exact prior behavior, and quoted/phrase arguments now parse. RFC 3501 §6.4.4 search-key arguments are `astring`, so accepting a quoted field on HEADER is also spec-correct. The criteria keyword itself still uses `parseAtom` — right call.

### Scope (Hoie's rule 1)
Clean. Two files, both directly on the quoted-string SEARCH path: the parser source (+1 import, 9 value-read swaps) and its sibling test. No drive-by edits.

### Tests
New `quoted-string criteria` describe block holds 5 it() cases (SUBJECT quoted single, SUBJECT quoted phrase, FROM quoted, BODY/TEXT quoted, HEADER quoted field+value) — verified by grep, not assumed. Ran `bun test src/server/lib/imap/parsers/search-parsers.test.ts` locally: 45 pass / 0 fail. (Note: PR body says "50 pass" — the file actually reports 45; the new block is correct regardless, just a stale count in the body.) Plain `.test.ts` edit of an existing file with no `pg`/`"server"`-barrel mocking, so no bundled-isolation requirement applies.

### CI
The 4 red `test`-job failures are all `IdleManager.notifyNewMail mailbox filtering > …` with `TypeError: idleManager.shutdown is not a function` — the known `handler-idle.test.ts` process-global `mock.module` leak into the idle-manager suite, fixed by the open PR #585. Confirmed by reading the runner log (run 27820713715): zero failures touch `search-parsers`. Not a defect of this PR.

### Low (informational)
- `SUBJECT ""` (empty quoted string) now parses to `{ type: "SUBJECT", value: "" }`, which flows into an `ILIKE '%%'` match-everything downstream. This is RFC-consistent (empty astring) and harmless — flagging only so it's a known behavior, not a request to change.

No further blockers.

— Generated by the inbox-reviewer agent.

**Review by hoiekim — APPROVED** [review]
